### ISSUE TITLE
unknown error occurred

### ISSUE THREAD

**Issue by youssef59600** [mawaqit-foundation/homeassistant-mawaqit#6]
Salam Alikoum Warahmatollah.  Après installation sur un raspberry, j’essaie d’ajouté l’intégration mais j’ai constamment une erreur « unknown error occurred » lorsque j’entre mes infos de connexion.

**Comment by yac69** [comment]
Salam Aleikom, deux choses peuvent expliquer ce problème . soit email/password de mawaqit erronés soit pas de coordonnées gps enregistrées dans home assistant. 

peux tu stp fournir le log de l'erreur: tu le retrouves en allant dans "outils de développement" dans la barre gauche de home assistant, puis dans "journaux", tu cherche mawaqit et ça te donne le log de l'erreur.

**Comment by youssef59600** [comment]
Alikoum Salam Warahmatollah,

Barkallah o fik pour ton support. Voici les log :

Détails du journal ( ERROR )
Logger: aiohttp.server
Source: custom_components/mawaqit/config_flow.py:96 
First occurred: 19:02:20 (1 occurrences) 
Last logged: 19:02:20

Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request, flow_id)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 153, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/home/homeassistant/.homeassistant/custom_components/mawaqit/config_flow.py", line 96, in async_step_user
    if not bool(response0.json()):
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/srv/homeassistant/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/srv/homeassistant/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0 )
——————///—————////——————————


Détails du journal ( WARNING )
Logger: homeassistant.util.async_
Source: util/async_.py:120 
First occurred: 19:02:19 (2 occurrences) 
Last logged: 19:02:19

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for mawaqit doing I/O at custom_components/mawaqit/config_flow.py, line 70: response = get(url, auth=(username, password))
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for mawaqit doing I/O at custom_components/mawaqit/config_flow.py, line 95: response0 = requests.get(api_url0, params=params, headers=headers)






Envoyé de mon iPhone

**Comment by yac69** [comment]
l'api de recherche de mosquée dans votre entourage a rencontré un problème.
tes coordonnées latitude/longitude dans home assistant ne sont pas visiblement rentrées. pour les saisir, deux façons
soit les rajouter dans le configuration.yaml
https://www.home-assistant.io/docs/configuration/basic/

soit le faire dans configuration>géneral : tu devrais avoir une carte pour y mettre tes coordonnées et puis enregistrer

tu me confirmes stp si ça marche une fois tu rajoutes ces coordonnées. en fonction de ton retour, je vais ajouter dans le code du plugin un check que ces coordonnées sont bien enregistrées avant d'aller cherche les mosquées les plus proches.

**Comment by youssef59600** [comment]
Barkallah o fik pour le dépannage rapide. L’ajout des coordonnées latitude, longitude et élévation dans le fichier configuration.yaml a corriger le problème. J’ai bien réussi à intégrer mawaqit.

Envoyé de mon iPhone

**Comment by yac69** [comment]
Barak All fik. je révise alors le plugin en conséquence pour vérifier la présence ou non des coordonnées GPS avant d'aller chercher les mosquées.

**Comment by youssef59600** [comment]
Wafik Baraka. Merci pour ton travail et la mise a disposition. Je vais
maintenant me mettre au travail pour la création des evenements

**Comment by youssef59600** [comment]
Juste un question stp frère. Je reprend ton exemple pour mettre en place la
conf dans configure.yaml, et j'ai une question sur par exemple la
premiere section :

automation:
- alias: Prayer Time Magreb
initial_state: true
trigger:
platform: template
value_template: >
{% set a1 = states("sensor.date_time").split(" ")[1].split(":")[0] %}
{% set b1 = states("sensor.date_time").split(":")[1] %}
{% set a = states("sensor.maghrib_mawaqit").split(" ")[1].split(":")[0] %}
{% set b = states("sensor.maghrib_mawaqit").split(":")[1] %}
{{ b | int == b1 | int and a | int == a1 | int }}
action: # the action below is given as an example and is to adapt based on
on your homeassistant installation
- service: mqtt.publish
data_template:
topic: 'commande/play/mini'




payload: "http://192.168.10.101/Quran/nofajr.mp3" J'ai un disuqe dur en
partage avec mon routeur ASUS ou j'ai mis un fichier Adhan.mp4 et j'ai
installer un broker local (mosquito sur le rasberry) puis mqtt sur le
homeassistant. pour la section ou j'appel le fichier adhan je dois mettre
le path du fichier juste après payload, mais pour la parti topic je laisse
comme cela ? Merci pour to aide barkallah o fik

**Comment by yac69** [comment]
Salem Aleikom

pour la partie action de cette automatisation, pas nécessaire d'avoir un broker. si tu as une entité de type media_player dans ton installation, tu peux lancer le service play_media
https://www.home-assistant.io/integrations/media_player/

dans mon example, j'ai un broker à qui j'envoie le topic 'commande/play/mini' et en payload l'adresse du mp3

le lien entre ce topic et le payload est fair dans nodered pour mon installation
<img width="836" alt="Capture d’écran 2020-07-02 à 19 41 37" src="https://user-images.githubusercontent.com/52980212/86394813-6f383d00-bc9f-11ea-9954-700a024c1285.png">

le nodered dès reception du topic et le payload, prends le lien mp3 du payload et le cast sur un google mini

**Comment by ChalidNL** [comment]
As salam arlaikum,

I had the issue related to mawaqit integration in Home Assistant. 

My fix:
- Used the latest version
- Created a new account within Mawaqit

And now it is working. Before it would not work.

**Comment by youssef59600** [comment]
Salam Alikoum Warahmatollah,

Tous d'abord  Moubarak Ramadan Kareem.

Je me permets de te recontacter, car j'ai un souci avec l'integration
mawaqit sur homeassistant. En faite je l'ai depuis le debut ca fonctionner
sans souci j'ai meme créer l'automatisation pour l 'adhan. C'est dernier
jours l'adhan ce faisait en retard de 1 ou 2 minute, c'était pas trop
gênant mais depuis hier c'est en avance et avec les enfants j'ai pas envie
qu'il romptent leur jeûne avant l'heure.

J'ai donc désinstaller l'intégration mais lorsque je la réinstall j'ai
l'erreur suivante :

Logger: homeassistant.config_entries
Source: custom_components/mawaqit/__init__.py:286
Integration: mawaqit
First occurred: 19:35:57 (1 occurrences)
Last logged: 19:35:57
Error setting up entry Mawaqit for mawaqit_prayer_times

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/mawaqit/__init__.py",
line 285, in async_setup
    await self.hass.async_add_executor_job(self.get_new_prayer_times)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mawaqit/__init__.py",
line 190, in get_new_prayer_times
    n = text_file.write(str(calc.fetch_prayer_times()))
  File "/srv/homeassistant/lib/python3.8/site-packages/mawaqit_times_calculator/pray_times_calculator.py",
line 94, in fetch_prayer_times
    s1 = response.json()["times"][0]
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/models.py",
line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/simplejson/__init__.py",
line 525, in loads
    return _default_decoder.decode(s)
  File "/srv/homeassistant/lib/python3.8/site-packages/simplejson/decoder.py",
line 370, in decode
    obj, end = self.raw_decode(s)
  File "/srv/homeassistant/lib/python3.8/site-packages/simplejson/decoder.py",
line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py",
line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/mawaqit/__init__.py",
line 72, in async_setup_entry
    if not await client.async_setup():
  File "/home/homeassistant/.homeassistant/custom_components/mawaqit/__init__.py",
line 286, in async_setup
    except (exceptions.InvalidResponseError, ConnError) as err:
NameError: name 'exceptions' is not defined


Peux tu m'aider à débuger stp ?


Barkallah o fik
